Employee_Mg_Asp.NetCore/Models/EmployeeMaster.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Employee_Mg_Asp.NetCore.Models
{
    public class EmployeeMaster
    {
        [Key]
        public int Employee_Id { get; set; }
        [Display(Name = "Employee Name")]
        [Required(ErrorMessage = "Please Enter Employee Name")]
        [RegularExpression(@"^[A-Z]+[a-zA-Z'\s]*$")]
        [StringLength(100, MinimumLength = 3)]
        public string Employee_Name { get; set; }


        public Nullable<int> Department_Id { get; set; }

        [Required(ErrorMessage = "Please Enter Employee Joining Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> JoiningDate { get; set; }

        [StringLength(200, MinimumLength = 3)]
        public string Address { get; set; }
        public Nullable<int> IsDelete { get; set; }

        [Display(Name = "Email Address")]
        [Required(ErrorMessage = "Email is required.")]
        [EmailAddress(ErrorMessage = "Invalid Email Address.")]
        [StringLength(60, MinimumLength = 8)]
        public string Email { get; set; }

        [Display(Name = "Contact No")]
        [StringLength(10, MinimumLength = 10)]
        public string MobileNo { get; set; }
        public string Image { get; set; }

        public virtual DepartmentMaster DepartmentMaster { get; set; }
    }
}

Employee_Mg_Asp.NetCore/Controllers/EmployeeMastersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Employee_Mg_Asp.NetCore.Data;
using Employee_Mg_Asp.NetCore.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using System.Net.Http.Headers;

namespace Employee_Mg_Asp.NetCore.Controllers
{
    public class EmployeeMastersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IHostingEnvironment _hostingEnvironment;

        public EmployeeMastersController(UserManager<ApplicationUser> userManager,
          SignInManager<ApplicationUser> signInManager, ApplicationDbContext context, IHostingEnvironment hostingEnvironment)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _context = context;
            _hostingEnvironment = hostingEnvironment;
        }

        // GET: EmployeeMasters
        public async Task<IActionResult> Index(string searchText, string sortOrder, string currentFilter, int? page)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return RedirectToAction("LogIn", "Account");
            }
            ViewData["Role"] = user.PhoneNumber;
            ViewData["Email"] = user.Email;
            ViewData["CurrentSort"] = sortOrder;
            ViewBag.idSortParm = String.IsNullOrEmpty(sortOrder) ? "Id" : "";
            ViewBag.NameSortParm = sortOrder == "Name" ? "name_desc" : "Name";
            ViewBag.EmailSortParm = sortOrder == "Email" ? "email_desc" : "Email";

            if (searchText != null)
            {
                page = 1;
            }
            else
            {
                searchText = currentFilter;
            }

            ViewBag.currentFilter = searchText;
            var employeeMasters = _context.EmployeeMaster.Include(e => e.DepartmentMaster).Where(e => e.IsDelete == 0 && e.DepartmentMaster.IsDelete == 0);
            if (!String.IsNullOrEmpty(searchText))
            {
                employeeMasters = employeeMasters.Where(s => s.Employee_Name.Contains(searchText) || s.Email.Contains(searchText) || s.Address.Contains(searchText) || s.JoiningDate.ToString().Contains(searchText) || s.DepartmentMaster.Department_Name.Contains(searchText));
            }
            switch (sortOrder)
            {
                case "Id":
                    employeeMasters = employeeMasters.OrderBy(s => s.Employee_Id);
                    break;
                case "name_desc":
                    employeeMasters = employeeMasters.OrderByDescending(s => s.Employee_Name);
                    break;
                case "Email":
                    employeeMasters = employeeMasters.OrderBy(s => s.Email);
                    break;
                case "email_desc":
                    employeeMasters = employeeMasters.OrderByDescending(s => s.Email);
                    break;
                default:
                    employeeMasters = employeeMasters.OrderBy(s => s.Employee_Name);
                    break;
            }
            ViewBag.path = Path.Combine(_hostingEnvironment.WebRootPath, "Emp_IMg");
            int pageSize = 3;
            return View(await PaginatedList<EmployeeMaster>.CreateAsync(employeeMasters.AsNoTracking(), page ?? 1, pageSize));
        }


        // GET: EmployeeMasters/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return RedirectToAction("LogIn", "Account");
            }
            if (id == null)
            {
                return NotFound();
            }

            var employeeMaster = await _context.EmployeeMaster
                .Include(e => e.DepartmentMaster)
                .SingleOrDefaultAsync(m => m.Employee_Id == id);
            ViewBag.image = employeeMaster.Image;
            ViewBag.path = Path.Combine(_hostingEnvironment.WebRootPath, "Emp_IMg");
            if (employeeMaster == null)
            {
                return NotFound();
            }

            return View(employeeMaster);
        }

        // GET: EmployeeMasters/Create
        public async Task<IActionResult> Create()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return RedirectToAction("LogIn", "Account");
            }
            if (user.PhoneNumber.ToString().Equals("GuestUser"))
            {
                return RedirectToAction("Index");
            }
            ViewData["Department_Id"] = new SelectList(_context.DepartmentMaster.Where(s => s.IsDelete == 0), "Department_Id", "Department_Name");
            return View();
        }

        // POST: EmployeeMasters/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Employee_Id,Employee_Name,Department_Id,JoiningDate,Address,Email,MobileNo,Image")] EmployeeMaster employeeMaster)
        {
            if (ModelState.IsValid)
            {
                if (_context.EmployeeMaster.Any(name => name.Email.Equals(employeeMaster.Email) && name.IsDelete == 0))
                {
                    ModelState.AddModelError(string.Empty, "Employee is already exists");
                    ViewData["Department_Id"] = new SelectList(_context.DepartmentMaster.Where(s => s.IsDelete == 0), "Department_Id", "Department_Name");
                    return View(employeeMaster);
                }

                else
                {
                    var files = HttpContext.Request.Form.Files;
                    foreach (var Image in files)
                    {
                        if (Image != null && Image.Length > 0)
                        {
                            var supportedTypes = new[] { "jpg", "jpeg", "png", "gif", "bmp" };
                            var fileExt = System.IO.Path.GetExtension(Image.FileName).Substring(1);
                            if (!supportedTypes.Contains(fileExt))
                            {
                                string ErrorMessage = "File Extension Is InValid - Only Upload Image File";
                                ModelState.AddModelError(string.Empty, ErrorMessage);
                                ViewData["Department_Id"] = new SelectList(_context.DepartmentMaster.Where(s => s.IsDelete == 0), "Department_Id", "Department_Name");
                                return View(employeeMaster);
                            }
                            var file = Image;
                            var uploads = Path.Combine(_hostingEnvironment.WebRootPath, "Emp_IMg");

                            if (file.Length > 0)
                            {
                                var fileName = ContentDispositionHeaderValue.Parse
                                    (file.ContentDisposition).FileName.ToString().Trim('"');

                                System.Console.WriteLine(fileName);
                                using (var fileStream = new FileStream(Path.Combine(uploads, file.FileName), FileMode.Create))
                                {
                                    await file.CopyToAsync(fileStream);
                                    employeeMaster.Image = file.FileName;
                                }


                            }
                        }
                    }
                    //employeeMaster.Department_Id = 2;
                    employeeMaster.IsDelete = 0;
                    _context.Add(employeeMaster);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            ViewData["Department_Id"] = new SelectList(_context.DepartmentMaster.Where(s => s.IsDelete == 0), "Department_Id", "Department_Name");
            return View(employeeMaster);
        }

        // GET: EmployeeMasters/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return RedirectToAction("LogIn", "Account");
            }
            var employeeMaster = await _context.EmployeeMaster.SingleOrDefaultAsync(m => m.Employee_Id == id);
            if (employeeMaster == null)
            {
                return NotFound();
            }
            if (user.PhoneNumber.ToString().Equals("GuestUser") && !user.Email.ToString().Equals(employeeMaster.Email))
            {
                return RedirectToAction("Index");
            }
            if (id == null)
            {
                return NotFound();
            }


            ViewData["Department_Id"] = new SelectList(_context.DepartmentMaster.Where(s => s.IsDelete == 0), "Department_Id", "Department_Name");
            return View(employeeMaster);
        }

        // POST: EmployeeMasters/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Employee_Id,Employee_Name,Department_Id,JoiningDate,Address,Email,MobileNo,Image")] EmployeeMaster employeeMaster)
        {
            //if (id != employeeMaster.Employee_Id)
            //{
            //    return NotFound();
            //}

            if (ModelState.IsValid)
            {
                try
                {
                    if (_context.EmployeeMaster.Any(name => name.Email.Equals(employeeMaster.Email) && name.Employee_Id != employeeMaster.Employee_Id && name.IsDelete == 0))
                    {

Employee_Mg_Asp.NetCore/Views/EmployeeMasters/Create.cshtml
@model Employee_Mg_Asp.NetCore.Models.EmployeeMaster

@{
	ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>EmployeeMaster</h4>
<hr />
@using (Html.BeginForm("Create", "EmployeeMasters", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
	@Html.AntiForgeryToken()

	<div class="row">
		<div class="col-md-4">
			<form asp-action="Create">
				<div asp-validation-summary="ModelOnly" class="text-danger"></div>
				<div class="form-group">
					<label asp-for="Employee_Name" class="control-label"></label>
					<input asp-for="Employee_Name" class="form-control" />
					<span asp-validation-for="Employee_Name" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="Department_Id" class="control-label"></label>
					<select asp-for="Department_Id" class="form-control" asp-items="ViewBag.Department_Id"></select>
				</div>
				<div class="form-group">
					<label asp-for="JoiningDate" class="control-label"></label>
					<input asp-for="JoiningDate" class="form-control" />
					<span asp-validation-for="JoiningDate" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="Address" class="control-label"></label>
					<input asp-for="Address" class="form-control" />
					<span asp-validation-for="Address" class="text-danger"></span>
				</div>
				
				<div class="form-group">
					<label asp-for="Email" class="control-label"></label>
					<input asp-for="Email" class="form-control" />
					<span asp-validation-for="Email" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="MobileNo" class="control-label"></label>
					<input asp-for="MobileNo" class="form-control" />
					<span asp-validation-for="MobileNo" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="Image" class="control-label"></label>
					<input asp-for="Image" class="form-control" type="file" name="pic" accept="image/*" />
					<span asp-validation-for="Image" class="text-danger"></span>
				</div>
				<div class="form-group">
					<input type="submit" value="Create" class="btn btn-default" />
				</div>
			</form>
		</div>
	</div>
}
	<div>
		<a asp-action="Index">Back to List</a>
	</div>

	@section Scripts {
		@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
	}

Employee_Mg_Asp.NetCore/Views/EmployeeMasters/Delete.cshtml
@model Employee_Mg_Asp.NetCore.Models.EmployeeMaster

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>


<div>
    <h4>EmployeeMaster</h4>
    <hr />
	<dl class="dl-horizontal">
		<dt>
			@Html.DisplayNameFor(model => model.Employee_Name)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.Employee_Name)
		</dd>
		<dt>
			@Html.DisplayNameFor(model => model.JoiningDate)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.JoiningDate)
		</dd>
		<dt>
			@Html.DisplayNameFor(model => model.Address)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.Address)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.Email)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.Email)
		</dd>
		<dt>
			@Html.DisplayNameFor(model => model.MobileNo)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.MobileNo)
		</dd>
		<dt>
			@Html.DisplayNameFor(model => model.DepartmentMaster)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.DepartmentMaster.Department_Name)
		</dd>
		<dt>
			@Html.DisplayNameFor(model => model.Image)
		</dt>
		<dd>
			@{
			if (System.IO.File.Exists(ViewBag.path + "/" + ViewBag.image))
			{
				<img src="~/Emp_IMg/@ViewBag.image"
					 asp-append-version="true" width=200 height=100 />
		}
			}
		</dd>

	</dl>
    
	<form asp-action="Delete">
		<input type="hidden" asp-for="Employee_Id" />
		<input type="submit" value="Delete" class="btn btn-default" onclick="return confirm('Are you Really wany to delete this employee?')" /> |
		<a asp-action="Index">Back to List</a>
	</form>
</div>

Employee_Mg_Asp.NetCore/Views/EmployeeMasters/Details.cshtml
@model Employee_Mg_Asp.NetCore.Models.EmployeeMaster

@{
	ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
	<h4>EmployeeMaster</h4>
	<hr />
	<dl class="dl-horizontal">
		<dt>
			@Html.DisplayNameFor(model => model.Employee_Name)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.Employee_Name)
		</dd>
		<dt>
			@Html.DisplayNameFor(model => model.JoiningDate)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.JoiningDate)
		</dd>
		<dt>
			@Html.DisplayNameFor(model => model.Address)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.Address)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.Email)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.Email)
		</dd>
		<dt>
			@Html.DisplayNameFor(model => model.MobileNo)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.MobileNo)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.DepartmentMaster)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.DepartmentMaster.Department_Name)
		</dd>
		<dt>
			@Html.DisplayNameFor(model => model.Image)
		</dt>
		<dd>
			@{
				if (System.IO.File.Exists(ViewBag.path + "/" + ViewBag.image))
				{
					<img src="~/Emp_IMg/@ViewBag.image"
						 asp-append-version="true" width=200 height=100 />
				}
			}
		</dd>
	</dl>
</div>
<div>
	<a asp-action="Index">Back to List</a>
</div>

Employee_Mg_Asp.NetCore/Views/EmployeeMasters/Edit.cshtml
@model Employee_Mg_Asp.NetCore.Models.EmployeeMaster

@{
	ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>EmployeeMaster</h4>
<hr />
@using (Html.BeginForm("Edit", "EmployeeMasters", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
	@Html.AntiForgeryToken()


	<div class="row">
		<div class="col-md-4">
			<form asp-action="Edit">
				<div asp-validation-summary="ModelOnly" class="text-danger"></div>
				<input type="hidden" asp-for="Employee_Id" />
				<div class="form-group">
					<label asp-for="Employee_Name" class="control-label"></label>
					<input asp-for="Employee_Name" class="form-control" />
					<span asp-validation-for="Employee_Name" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="Department_Id" class="control-label"></label>
					<select asp-for="Department_Id" class="form-control" asp-items="ViewBag.Department_Id"></select>
					<span asp-validation-for="Department_Id" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="JoiningDate" class="control-label"></label>
					<input asp-for="JoiningDate" class="form-control" />
					<span asp-validation-for="JoiningDate" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="Address" class="control-label"></label>
					<input asp-for="Address" class="form-control" />
					<span asp-validation-for="Address" class="text-danger"></span>
				</div>
				
				<div class="form-group">
					<label asp-for="Email" class="control-label"></label>
					<input asp-for="Email" class="form-control" />
					<span asp-validation-for="Email" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="MobileNo" class="control-label"></label>
					<input asp-for="MobileNo" class="form-control" />
					<span asp-validation-for="MobileNo" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="Image" class="control-label"></label>
					<input asp-for="Image" class="form-control" type="file" name="pic" accept="image/*" />
					<span asp-validation-for="Image" class="text-danger"></span>
				</div>
				<div class="form-group">
					<input type="submit" value="Save" class="btn btn-default" />
				</div>
			</form>
		</div>
	</div>
}
	<div>
		<a asp-action="Index">Back to List</a>
	</div>

	@section Scripts {
		@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
	}

Employee_Mg_Asp.NetCore/Views/EmployeeMasters/Index.cshtml
@model PaginatedList<Employee_Mg_Asp.NetCore.Models.EmployeeMaster>


@{
	ViewData["Title"] = "Index";
}

<h2>Index</h2>
<form asp-controller="EmployeeMasters" asp-action="Index" method="get">
	<p>
		Search : <input type="text" name="searchText" value="@ViewData["currentFilter"]">
		<input type="submit" value="Search" />
	</p>
</form>
@if (ViewData["Role"].ToString().Equals("AdminUser"))
{
	<p>
		<a asp-action="Create">Create New</a>
	</p>
}
<table class="table">
	<thead>
		<tr>
			<th>
				<a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]"
				   asp-route-currentFilter="@ViewData["CurrentFilter"]">
					Employee Name
				</a>
			</th>
			<th>
				JoiningDate
			</th>
			<th>
				Address
			</th>

			<th>
				<a asp-action="Index" asp-route-sortOrder="@ViewData["EmailSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">
					Employee Email
				</a>
			</th>
			<th>
				MobileNo
			</th>
			<th>
				Image
			</th>
			<th>
				Department
			</th>
			@if (ViewData["Role"].ToString().Equals("AdminUser"))

			{
				<th>Action</th>}
			@if (ViewData["Role"].ToString().Equals("GuestUser"))

			{
				<th>Action</th>}
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.Employee_Name)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.JoiningDate)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Address)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Email)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.MobileNo)
				</td>
				<td>
					@{
						if (System.IO.File.Exists(ViewBag.path + "/" + item.Image))
						{
							<img src="~/Emp_IMg/@item.Image" asp-append-version="true" width=200 height=100 />
						}
					}
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.DepartmentMaster.Department_Name)
				</td>
				@if (ViewData["Role"].ToString().Equals("AdminUser"))
				{
					<td>
						<a asp-action="Edit" asp-route-id="@item.Employee_Id">Edit</a> |
						<a asp-action="Details" asp-route-id="@item.Employee_Id">Details</a> |
						<a asp-action="Delete" asp-route-id="@item.Employee_Id">Delete</a>
					</td>}
				@if (ViewData["Role"].ToString().Equals("GuestUser"))
				{
					@if (ViewData["Email"].ToString().Equals(item.Email))

					{
						<td>
							<a asp-action="Edit" asp-route-id="@item.Employee_Id">Edit</a> |
							<a asp-action="Details" asp-route-id="@item.Employee_Id">Details</a> |
							<a asp-action="Delete" asp-route-id="@item.Employee_Id">Delete</a>
						</td>}
					@if (!ViewData["Email"].ToString().Equals(item.Email))

					{
						<td>

							<a asp-action="Details" asp-route-id="@item.Employee_Id">Details</a>
						</td>}
				}
			</tr>
		}
	</tbody>
</table>


@{
	var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
	var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-page="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled">
	Previous
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-page="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled">
	Next
</a>